name = "MonkeyLang"
uuid = "2e3b8ffb-b112-4a86-975c-b56a8cdf8971"
version = "0.2.3"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"

[compat]
Printf = "1"
ReplMaker = "0.2"
julia = "1.10"
